# Generated by Django 4.0.4 on 2022-06-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
