# Generated by Django 4.0.4 on 2022-06-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
    ]
